import {
  ProductChildren,
  ProductDetail,
  ProductFields,
} from "@/app/(dashboard)/products/actions";
import { ProductFormValues } from "@/app/(dashboard)/products/validation";
import { toDateInput, toFormString } from "@/lib/helpers";

// An empty string from a `<select>` means "unset", which the column stores as
// NULL. Numeric inputs behave the same way: a blank box is an absent figure,
// not a zero.
//
// Generic so an enum field keeps its literal union on the way through — a
// widened `string` would not satisfy the column's type.
const orNull = <T extends string>(value: T | "" | undefined): T | null =>
  value === "" || value === undefined ? null : value;

const numberOrNull = (value: string | undefined) =>
  value === undefined || value === "" ? null : Number(value);

/**
 * Everything the product form edits, as the Products columns. Derived figures
 * (theoretical weight rollups, stock on hand) are not here — those are written
 * by the processes that own them, never by this form.
 */
export const productFormToFields = (
  values: ProductFormValues,
): ProductFields => ({
  productCode: values.productCode,
  name: values.name,
  productGroupUuid: orNull(values.productGroupUuid),
  revenueGroupUuid: orNull(values.revenueGroupUuid),
  companyUuid: orNull(values.companyUuid),
  priceGroup: orNull(values.priceGroup),
  ean: orNull(values.ean),
  oldProductCode: orNull(values.oldProductCode),
  materialGroup: orNull(values.materialGroup),
  commodityCode: orNull(values.commodityCode),
  scrap: values.scrap,
  packaging: values.packaging,
  descSalesPurchaseOverridable: values.descSalesPurchaseOverridable,
  searchCode1: orNull(values.searchCode1),
  searchCode2: orNull(values.searchCode2),
  searchCode3: orNull(values.searchCode3),
  articleGroup: orNull(values.articleGroup),

  groupLongDesc: orNull(values.groupLongDesc),
  groupShortDesc: orNull(values.groupShortDesc),
  productShortDesc: orNull(values.productShortDesc),
  selectionCodes: values.selectionCodes,

  dimensionShape: orNull(values.dimensionShape),
  length: orNull(values.length),
  widthDiameter: orNull(values.widthDiameter),
  thickness: orNull(values.thickness),
  tradeLength: orNull(values.tradeLength),
  tradeLengthFixed: values.tradeLengthFixed,
  overlength: orNull(values.overlength),
  weightPerM1: orNull(values.weightPerM1),
  paintSurfacePerM1: orNull(values.paintSurfacePerM1),
  featuresQuality: orNull(values.featuresQuality),
  decimalPlaces: orNull(values.decimalPlaces),
  printDimensions: values.printDimensions,
  weightTheoretical: orNull(values.weightTheoretical),
  weightTrade: orNull(values.weightTrade),
  weightGerman: orNull(values.weightGerman),
  standardsQuality: orNull(values.standardsQuality),
  tolerance: orNull(values.tolerance),
  ce: orNull(values.ce),
  options: values.options,
  processedOption: orNull(values.processedOption),
  sourceProductUuid: orNull(values.sourceProductUuid),
  industryNumber: orNull(values.industryNumber),

  classificationMaterial: orNull(values.classificationMaterial),
  classificationQualityGroup: orNull(values.classificationQualityGroup),
  classificationMainShape: orNull(values.classificationMainShape),
  classificationSubShape: orNull(values.classificationSubShape),
  classificationProcedure: orNull(values.classificationProcedure),
  classificationAppearance: orNull(values.classificationAppearance),
  classificationPerformance: orNull(values.classificationPerformance),

  purchasingUnit: orNull(values.purchasingUnit),
  unitPrice: orNull(values.unitPrice),
  deliveryTime: numberOrNull(values.deliveryTime),
  deliveryTimeUnit: orNull(values.deliveryTimeUnit),
  orderSeries: numberOrNull(values.orderSeries),
  blockedForPurchasing: values.blockedForPurchasing,
  makingOrderAdvices: values.makingOrderAdvices,
  visibleInProductionSchedule: values.visibleInProductionSchedule,
  orderingAdviceNotes: orNull(values.orderingAdviceNotes),
  productCodeOnPurchase: values.productCodeOnPurchase,
  maxLineQty: orNull(values.maxLineQty),
  maxNetPrice: orNull(values.maxNetPrice),

  salesUnit: orNull(values.salesUnit),
  salesUnitPrice: orNull(values.salesUnitPrice),
  vatCode: orNull(values.vatCode),
  roundWeightPerPieceUp: values.roundWeightPerPieceUp,
  benorProduct: values.benorProduct,
  productCodeOnQuoteOrderInvoice: values.productCodeOnQuoteOrderInvoice,
  certificaat: orNull(values.certificaat),
  websiteExport: values.websiteExport,
  websiteBlockedForSales: values.websiteBlockedForSales,
  descriptionProductShort: values.descriptionProductShort,
  showWeightPerPiece: values.showWeightPerPiece,
  showPackagingPerPiece: values.showPackagingPerPiece,
  markProductGroup: values.markProductGroup,
  priceOnRequest: values.priceOnRequest,
  minProfitMarginStock: orNull(values.minProfitMarginStock),
  minProfitMarginExWorks: orNull(values.minProfitMarginExWorks),
  minProfitMarginCrossDocking: orNull(values.minProfitMarginCrossDocking),
  severalBlockedForSales: values.severalBlockedForSales,
  vehicleWithCraneRequired: values.vehicleWithCraneRequired,
  vehicleWithCanopyRequired: values.vehicleWithCanopyRequired,
  alwaysReserveStock: values.alwaysReserveStock,
  maxSalesLineQty: orNull(values.maxSalesLineQty),
  maxSalesNetPrice: orNull(values.maxSalesNetPrice),
  handlingCosts: orNull(values.handlingCosts),

  packagingMandatoryOnCompletion: values.packagingMandatoryOnCompletion,
  unloadingWorkorderInStockUnit: values.unloadingWorkorderInStockUnit,
  receiptInLocationsWithLimitedDimensions:
    values.receiptInLocationsWithLimitedDimensions,
  goodsReceiptTerm: numberOrNull(values.goodsReceiptTerm),
  includeInCsvForStockLabels: values.includeInCsvForStockLabels,
  suggestLastUsedChargeInScanner: values.suggestLastUsedChargeInScanner,
  stockLabelType: orNull(values.stockLabelType),
  stockLabelBreakdown: orNull(values.stockLabelBreakdown),
  stockLabelPieces: numberOrNull(values.stockLabelPieces),
  toleranceUnloadingQty: orNull(values.toleranceUnloadingQty),
  toleranceUnloadingKg: orNull(values.toleranceUnloadingKg),
  toleranceCountQty: orNull(values.toleranceCountQty),
  toleranceCountKg: orNull(values.toleranceCountKg),
  tolerancePickingQty: orNull(values.tolerancePickingQty),
  tolerancePickingKg: orNull(values.tolerancePickingKg),
  toleranceProductionQty: orNull(values.toleranceProductionQty),
  customerLabelForPickingSlip: orNull(values.customerLabelForPickingSlip),
  customerLabelForSawingSlip: orNull(values.customerLabelForSawingSlip),
  customerLabelAtSurfTreatSlip: orNull(values.customerLabelAtSurfTreatSlip),
  alwaysApproveManuallyWarehouseWorkorderLine:
    values.alwaysApproveManuallyWarehouseWorkorderLine,
  alwaysApproveManuallyProductionWorkorderLine:
    values.alwaysApproveManuallyProductionWorkorderLine,

  minStockMode: values.minStockMode,
  minStockMultiplier: orNull(values.minStockMultiplier),
  minStockFixedValue: orNull(values.minStockFixedValue),
  maxStockMode: values.maxStockMode,
  maxStockMultiplier: orNull(values.maxStockMultiplier),
  maxStockFixedValue: orNull(values.maxStockFixedValue),
  leadTimeMethod: orNull(values.leadTimeMethod),
  leadTime: numberOrNull(values.leadTime),
  reviewPeriod: numberOrNull(values.reviewPeriod),
  orderCostsPurchasingSide: orNull(values.orderCostsPurchasingSide),
  orderCostsLogistics: orNull(values.orderCostsLogistics),
  stockOpOrderSeries: orNull(values.stockOpOrderSeries),
  minOrderQty: orNull(values.minOrderQty),
  useStockOpForThisProduct: values.useStockOpForThisProduct,
  orderOnMonday: values.orderOnMonday,
  orderOnTuesday: values.orderOnTuesday,
  orderOnWednesday: values.orderOnWednesday,
  orderOnThursday: values.orderOnThursday,
  orderOnFriday: values.orderOnFriday,
  capitalCost: orNull(values.capitalCost),
  warehouseCost: orNull(values.warehouseCost),
  b2StockoutPct1: orNull(values.b2StockoutPct1),
  b2StockoutPct2: orNull(values.b2StockoutPct2),
  handling: orNull(values.handling),
  transport: orNull(values.transport),
  pacClassification: orNull(values.pacClassification),
  orderAdviceCode: orNull(values.orderAdviceCode),

  stockUnit: orNull(values.stockUnit),
  scrapProductUuid: orNull(values.scrapProductUuid),
  transferProductUuid: orNull(values.transferProductUuid),
  packagingProductUuid: orNull(values.packagingProductUuid),
  cdLocationUuid: orNull(values.cdLocationUuid),
  stockProduct: values.stockProduct,
  stockProductSince: orNull(values.stockProductSince),
  standardProduct: values.standardProduct,
  groupProduct: values.groupProduct,
  batchRegistration: values.batchRegistration,
  batchRegisterLength: values.batchRegisterLength,
  batchLengthMinimum: orNull(values.batchLengthMinimum),
  batchLengthInterval: orNull(values.batchLengthInterval),
  batchLengthRemainderTolerance: orNull(values.batchLengthRemainderTolerance),
  batchRegisterWidth: values.batchRegisterWidth,
  batchWidthMinimum: orNull(values.batchWidthMinimum),
  batchWidthInterval: orNull(values.batchWidthInterval),
  batchUseOptimization: values.batchUseOptimization,
  batchCharge: values.batchCharge,
  batchDispatchStrategy: orNull(values.batchDispatchStrategy),
  batchDoNotSplitPerBatch: values.batchDoNotSplitPerBatch,
  batchPlateNumber: values.batchPlateNumber,
  batchPerPiece: values.batchPerPiece,
  batchNumber: values.batchNumber,
  countFrequency: numberOrNull(values.countFrequency),
  lastCountDate: orNull(values.lastCountDate),
  nextCountTargetDate: orNull(values.nextCountTargetDate),
  countStockBasis: orNull(values.countStockBasis),
  countBelowQuantity: orNull(values.countBelowQuantity),
  countBelowUnit: orNull(values.countBelowUnit),

  optTradeLengthTolerance: numberOrNull(values.optTradeLengthTolerance),
  optEndSpace: numberOrNull(values.optEndSpace),
  optClamping: numberOrNull(values.optClamping),
  optOffcutMinLength: numberOrNull(values.optOffcutMinLength),
  optOffcutPreferredMin: numberOrNull(values.optOffcutPreferredMin),
  optClampingEdge: numberOrNull(values.optClampingEdge),
  optFactorBundles: numberOrNull(values.optFactorBundles),
  optFactorPriorityLocationType: numberOrNull(
    values.optFactorPriorityLocationType,
  ),
  optFactorSawingCuts: numberOrNull(values.optFactorSawingCuts),
  optFactorCreatedOffcuts: numberOrNull(values.optFactorCreatedOffcuts),
  optFactorCreatedScrapPieces: numberOrNull(values.optFactorCreatedScrapPieces),
  optFactorUsedTradeLengths: numberOrNull(values.optFactorUsedTradeLengths),
  optFactorUsedOffcuts: numberOrNull(values.optFactorUsedOffcuts),
  optFactorScrapPieceLength: numberOrNull(values.optFactorScrapPieceLength),
  optFactorOffcutsBelowPreferred: numberOrNull(
    values.optFactorOffcutsBelowPreferred,
  ),
  optFactorLengthCutoffs: numberOrNull(values.optFactorLengthCutoffs),
  optAllowLongestOffcuts: values.optAllowLongestOffcuts,

  basePrice: orNull(values.basePrice),
  markup: orNull(values.markup),
  fixedSalesPrice: orNull(values.fixedSalesPrice),
  priceUnit: orNull(values.priceUnit),
  priceDate: orNull(values.priceDate),

  technicalStock: values.technicalStock,
  theoreticalWeight: values.theoreticalWeight,
  weightUnit: orNull(values.weightUnit),
  showOnWebsite: values.showOnWebsite,
  preferred: values.preferred,
  externalProductCode: orNull(values.externalProductCode),
  editing: orNull(values.editing),
  remarks: orNull(values.remarks),
  documents: values.documents?.length ? values.documents : null,
});

export const productFormToChildren = (
  values: ProductFormValues,
): ProductChildren => ({
  alternatives: values.alternatives.map((row) => ({
    alternativeProductUuid: row.alternativeProductUuid,
    description: orNull(row.description),
  })),
  suppliers: values.suppliers.map((row) => ({
    supplierUuid: row.supplierUuid,
    preferred: row.preferred,
    ean: orNull(row.ean),
    externalProductCode: orNull(row.externalProductCode),
    editing: orNull(row.editing),
    deliveryTime: numberOrNull(row.deliveryTime),
    deliveryTimeUnit: orNull(row.deliveryTimeUnit),
    minOrderQty: orNull(row.minOrderQty),
    minOrderQtyUnit: orNull(row.minOrderQtyUnit),
    orderSeries: orNull(row.orderSeries),
    orderSeriesUnit: orNull(row.orderSeriesUnit),
  })),
  preferredLocations: values.preferredLocations.map((row) => ({
    locationUuid: row.locationUuid,
    restockLocationUuid: orNull(row.restockLocationUuid),
    preference: numberOrNull(row.preference),
    locationType: orNull(row.locationType),
    restockLevel: orNull(row.restockLevel),
    restockLevelUnit: orNull(row.restockLevelUnit),
    restockQty: orNull(row.restockQty),
    restockQtyUnit: orNull(row.restockQtyUnit),
  })),
  priceStructures: values.priceStructures.map((row) => ({
    validFrom: row.validFrom,
    validUntil: orNull(row.validUntil),
    basePrice: orNull(row.basePrice),
    markup: orNull(row.markup),
    scrap: orNull(row.scrap),
    priceUnit: orNull(row.priceUnit),
    quantitySurchargeEnabled: row.quantitySurchargeEnabled,
    quantitySurchargeBasis: orNull(row.quantitySurchargeBasis),
    quantitySurchargeTiers: row.quantitySurchargeTiers,
    groupDiscountEnabled: row.groupDiscountEnabled,
    groupDiscountBasis: orNull(row.groupDiscountBasis),
    groupDiscountTiers: row.groupDiscountTiers,
    lengthSurchargeEnabled: row.lengthSurchargeEnabled,
    lengthSurchargeTiers: row.lengthSurchargeTiers,
    qualitySurchargeEnabled: row.qualitySurchargeEnabled,
    qualitySurchargeTiers: row.qualitySurchargeTiers,
    lineDiscountEnabled: row.lineDiscountEnabled,
    lineDiscountTiers: row.lineDiscountTiers,
  })),
  sawingPrices: values.sawingPrices.map((row) => ({
    validFrom: row.validFrom,
    validUntil: orNull(row.validUntil),
    basePrice: orNull(row.basePrice),
    priceUnit: orNull(row.priceUnit),
    mitreSurchargeEvenPct: orNull(row.mitreSurchargeEvenPct),
    mitreSurchargeUnevenPct: orNull(row.mitreSurchargeUnevenPct),
    quantityDiscountEnabled: row.quantityDiscountEnabled,
    quantityDiscountTiers: row.quantityDiscountTiers,
    lengthSurchargeEnabled: row.lengthSurchargeEnabled,
    lengthSurchargeTiers: row.lengthSurchargeTiers,
  })),
});


/** A saved product back into the values its form edits. */
export const productDetailToFormValues = (
  product: ProductDetail,
): ProductFormValues => ({
  productCode: product.productCode,
  name: product.name,
  productGroupUuid: toFormString(product.productGroupUuid),
  revenueGroupUuid: toFormString(product.revenueGroupUuid),
  companyUuid: toFormString(product.companyUuid),
  priceGroup: toFormString(product.priceGroup),
  ean: toFormString(product.ean),
  oldProductCode: toFormString(product.oldProductCode),
  materialGroup: toFormString(product.materialGroup),
  commodityCode: toFormString(product.commodityCode),
  scrap: product.scrap ?? false,
  packaging: product.packaging ?? false,
  descSalesPurchaseOverridable: product.descSalesPurchaseOverridable ?? false,
  searchCode1: toFormString(product.searchCode1),
  searchCode2: toFormString(product.searchCode2),
  searchCode3: toFormString(product.searchCode3),
  articleGroup: product.articleGroup ?? "",

  groupLongDesc: toFormString(product.groupLongDesc),
  groupShortDesc: toFormString(product.groupShortDesc),
  productShortDesc: toFormString(product.productShortDesc),
  selectionCodes: product.selectionCodes ?? [],

  dimensionShape: product.dimensionShape ?? "",
  length: toFormString(product.length),
  widthDiameter: toFormString(product.widthDiameter),
  thickness: toFormString(product.thickness),
  tradeLength: toFormString(product.tradeLength, "0.00"),
  tradeLengthFixed: product.tradeLengthFixed ?? false,
  overlength: toFormString(product.overlength, "0.00"),
  weightPerM1: toFormString(product.weightPerM1, "0.0000"),
  paintSurfacePerM1: toFormString(product.paintSurfacePerM1, "0.0000"),
  featuresQuality: product.featuresQuality ?? "",
  decimalPlaces: product.decimalPlaces ?? "0",
  printDimensions: product.printDimensions ?? false,
  weightTheoretical: toFormString(product.weightTheoretical, "0.000"),
  weightTrade: toFormString(product.weightTrade, "0.000"),
  weightGerman: toFormString(product.weightGerman, "0.000"),
  standardsQuality: product.standardsQuality ?? "",
  tolerance: product.tolerance ?? "",
  ce: product.ce ?? "",
  options: product.options ?? [],
  processedOption: product.processedOption ?? "",
  sourceProductUuid: toFormString(product.sourceProductUuid),
  industryNumber: toFormString(product.industryNumber),

  classificationMaterial: toFormString(product.classificationMaterial),
  classificationQualityGroup: toFormString(product.classificationQualityGroup),
  classificationMainShape: toFormString(product.classificationMainShape),
  classificationSubShape: toFormString(product.classificationSubShape),
  classificationProcedure: toFormString(product.classificationProcedure),
  classificationAppearance: toFormString(product.classificationAppearance),
  classificationPerformance: toFormString(product.classificationPerformance),

  purchasingUnit: product.purchasingUnit ?? "",
  unitPrice: product.unitPrice ?? "",
  deliveryTime: toFormString(product.deliveryTime, "0"),
  deliveryTimeUnit: product.deliveryTimeUnit ?? "",
  orderSeries: toFormString(product.orderSeries, "0"),
  blockedForPurchasing: product.blockedForPurchasing ?? false,
  makingOrderAdvices: product.makingOrderAdvices ?? false,
  visibleInProductionSchedule: product.visibleInProductionSchedule ?? false,
  orderingAdviceNotes: toFormString(product.orderingAdviceNotes),
  productCodeOnPurchase: product.productCodeOnPurchase ?? false,
  maxLineQty: toFormString(product.maxLineQty, "0.00"),
  maxNetPrice: toFormString(product.maxNetPrice, "0.00"),

  salesUnit: product.salesUnit ?? "",
  salesUnitPrice: product.salesUnitPrice ?? "",
  vatCode: product.vatCode ?? "",
  roundWeightPerPieceUp: product.roundWeightPerPieceUp ?? false,
  benorProduct: product.benorProduct ?? false,
  productCodeOnQuoteOrderInvoice:
    product.productCodeOnQuoteOrderInvoice ?? false,
  certificaat: product.certificaat ?? "",
  websiteExport: product.websiteExport ?? false,
  websiteBlockedForSales: product.websiteBlockedForSales ?? false,
  descriptionProductShort: product.descriptionProductShort ?? false,
  showWeightPerPiece: product.showWeightPerPiece ?? false,
  showPackagingPerPiece: product.showPackagingPerPiece ?? false,
  markProductGroup: product.markProductGroup ?? false,
  priceOnRequest: product.priceOnRequest ?? false,
  minProfitMarginStock: toFormString(product.minProfitMarginStock, "0.00"),
  minProfitMarginExWorks: toFormString(product.minProfitMarginExWorks, "0.00"),
  minProfitMarginCrossDocking: toFormString(product.minProfitMarginCrossDocking, "0.00"),
  severalBlockedForSales: product.severalBlockedForSales ?? false,
  vehicleWithCraneRequired: product.vehicleWithCraneRequired ?? false,
  vehicleWithCanopyRequired: product.vehicleWithCanopyRequired ?? false,
  alwaysReserveStock: product.alwaysReserveStock ?? false,
  maxSalesLineQty: toFormString(product.maxSalesLineQty, "0.000"),
  maxSalesNetPrice: toFormString(product.maxSalesNetPrice, "0.00"),
  handlingCosts: toFormString(product.handlingCosts, "0.00"),

  packagingMandatoryOnCompletion:
    product.packagingMandatoryOnCompletion ?? false,
  unloadingWorkorderInStockUnit: product.unloadingWorkorderInStockUnit ?? false,
  receiptInLocationsWithLimitedDimensions:
    product.receiptInLocationsWithLimitedDimensions ?? false,
  goodsReceiptTerm: toFormString(product.goodsReceiptTerm, "0"),
  includeInCsvForStockLabels: product.includeInCsvForStockLabels ?? false,
  suggestLastUsedChargeInScanner:
    product.suggestLastUsedChargeInScanner ?? false,
  stockLabelType: product.stockLabelType ?? "",
  stockLabelBreakdown: product.stockLabelBreakdown ?? "per_line_bundle",
  stockLabelPieces: toFormString(product.stockLabelPieces, "1"),
  toleranceUnloadingQty: toFormString(product.toleranceUnloadingQty, "0.00"),
  toleranceUnloadingKg: toFormString(product.toleranceUnloadingKg, "0.00"),
  toleranceCountQty: toFormString(product.toleranceCountQty, "0.00"),
  toleranceCountKg: toFormString(product.toleranceCountKg, "0.00"),
  tolerancePickingQty: toFormString(product.tolerancePickingQty, "0.00"),
  tolerancePickingKg: toFormString(product.tolerancePickingKg, "0.00"),
  toleranceProductionQty: toFormString(product.toleranceProductionQty, "0.00"),
  customerLabelForPickingSlip: product.customerLabelForPickingSlip ?? "",
  customerLabelForSawingSlip: product.customerLabelForSawingSlip ?? "",
  customerLabelAtSurfTreatSlip: product.customerLabelAtSurfTreatSlip ?? "",
  alwaysApproveManuallyWarehouseWorkorderLine:
    product.alwaysApproveManuallyWarehouseWorkorderLine ?? false,
  alwaysApproveManuallyProductionWorkorderLine:
    product.alwaysApproveManuallyProductionWorkorderLine ?? false,

  minStockMode: product.minStockMode ?? "multiplier",
  minStockMultiplier: toFormString(product.minStockMultiplier, "1.00"),
  minStockFixedValue: toFormString(product.minStockFixedValue, "0.000"),
  maxStockMode: product.maxStockMode ?? "multiplier",
  maxStockMultiplier: toFormString(product.maxStockMultiplier, "3.00"),
  maxStockFixedValue: toFormString(product.maxStockFixedValue, "0.000"),
  leadTimeMethod: product.leadTimeMethod ?? "manually",
  leadTime: toFormString(product.leadTime, "0"),
  reviewPeriod: toFormString(product.reviewPeriod, "0"),
  orderCostsPurchasingSide: toFormString(product.orderCostsPurchasingSide, "0.00"),
  orderCostsLogistics: toFormString(product.orderCostsLogistics, "0.00"),
  stockOpOrderSeries: toFormString(product.stockOpOrderSeries, "0.000"),
  minOrderQty: toFormString(product.minOrderQty, "0.000"),
  useStockOpForThisProduct: product.useStockOpForThisProduct ?? false,
  orderOnMonday: product.orderOnMonday ?? true,
  orderOnTuesday: product.orderOnTuesday ?? true,
  orderOnWednesday: product.orderOnWednesday ?? true,
  orderOnThursday: product.orderOnThursday ?? true,
  orderOnFriday: product.orderOnFriday ?? true,
  capitalCost: toFormString(product.capitalCost, "0.0000"),
  warehouseCost: toFormString(product.warehouseCost, "0.0000"),
  b2StockoutPct1: toFormString(product.b2StockoutPct1, "0.00"),
  b2StockoutPct2: toFormString(product.b2StockoutPct2, "0.00"),
  handling: toFormString(product.handling, "0.0000"),
  transport: toFormString(product.transport, "0.0000"),
  pacClassification: toFormString(product.pacClassification),
  orderAdviceCode: toFormString(product.orderAdviceCode),

  stockUnit: product.stockUnit ?? "",
  scrapProductUuid: toFormString(product.scrapProductUuid),
  transferProductUuid: toFormString(product.transferProductUuid),
  packagingProductUuid: toFormString(product.packagingProductUuid),
  cdLocationUuid: toFormString(product.cdLocationUuid),
  stockProduct: product.stockProduct ?? false,
  stockProductSince: toDateInput(product.stockProductSince),
  standardProduct: product.standardProduct ?? false,
  groupProduct: product.groupProduct ?? false,
  batchRegistration: product.batchRegistration ?? false,
  batchRegisterLength: product.batchRegisterLength ?? false,
  batchLengthMinimum: toFormString(product.batchLengthMinimum, "0.00"),
  batchLengthInterval: toFormString(product.batchLengthInterval, "0.00"),
  batchLengthRemainderTolerance: toFormString(
    product.batchLengthRemainderTolerance,
    "0.00",
  ),
  batchRegisterWidth: product.batchRegisterWidth ?? false,
  batchWidthMinimum: toFormString(product.batchWidthMinimum, "0.00"),
  batchWidthInterval: toFormString(product.batchWidthInterval, "0.00"),
  batchUseOptimization: product.batchUseOptimization ?? false,
  batchCharge: product.batchCharge ?? false,
  batchDispatchStrategy: product.batchDispatchStrategy ?? "lifo",
  batchDoNotSplitPerBatch: product.batchDoNotSplitPerBatch ?? false,
  batchPlateNumber: product.batchPlateNumber ?? false,
  batchPerPiece: product.batchPerPiece ?? false,
  batchNumber: product.batchNumber ?? false,
  countFrequency: toFormString(product.countFrequency, "0"),
  lastCountDate: toDateInput(product.lastCountDate),
  nextCountTargetDate: toDateInput(product.nextCountTargetDate),
  countStockBasis: product.countStockBasis ?? "technical",
  countBelowQuantity: toFormString(product.countBelowQuantity, "0.000"),
  countBelowUnit: product.countBelowUnit ?? "",

  optTradeLengthTolerance: toFormString(product.optTradeLengthTolerance, "0"),
  optEndSpace: toFormString(product.optEndSpace, "0"),
  optClamping: toFormString(product.optClamping, "0"),
  optOffcutMinLength: toFormString(product.optOffcutMinLength, "0"),
  optOffcutPreferredMin: toFormString(product.optOffcutPreferredMin, "0"),
  optClampingEdge: toFormString(product.optClampingEdge, "0"),
  optFactorBundles: toFormString(product.optFactorBundles, "0"),
  optFactorPriorityLocationType: toFormString(
    product.optFactorPriorityLocationType,
    "0",
  ),
  optFactorSawingCuts: toFormString(product.optFactorSawingCuts, "0"),
  optFactorCreatedOffcuts: toFormString(product.optFactorCreatedOffcuts, "0"),
  optFactorCreatedScrapPieces: toFormString(product.optFactorCreatedScrapPieces, "0"),
  optFactorUsedTradeLengths: toFormString(product.optFactorUsedTradeLengths, "0"),
  optFactorUsedOffcuts: toFormString(product.optFactorUsedOffcuts, "0"),
  optFactorScrapPieceLength: toFormString(product.optFactorScrapPieceLength, "0"),
  optFactorOffcutsBelowPreferred: toFormString(
    product.optFactorOffcutsBelowPreferred,
    "0",
  ),
  optFactorLengthCutoffs: toFormString(product.optFactorLengthCutoffs, "0"),
  optAllowLongestOffcuts: product.optAllowLongestOffcuts ?? false,

  basePrice: toFormString(product.basePrice, "0.00"),
  markup: toFormString(product.markup, "0.00"),
  fixedSalesPrice: toFormString(product.fixedSalesPrice, "0.00"),
  priceUnit: product.priceUnit ?? "",
  priceDate: toDateInput(product.priceDate),

  technicalStock: toFormString(product.technicalStock, "0.000"),
  theoreticalWeight: toFormString(product.theoreticalWeight, "0.0000"),
  weightUnit: product.weightUnit ?? "",
  showOnWebsite: product.showOnWebsite ?? false,
  preferred: product.preferred ?? false,
  externalProductCode: toFormString(product.externalProductCode),
  editing: toFormString(product.editing),
  remarks: toFormString(product.remarks),
  documents: product.documents ?? [],

  alternatives: product.alternatives.map((row) => ({
    alternativeProductUuid: row.alternativeProductUuid,
    description: toFormString(row.description),
  })),
  suppliers: product.suppliers.map((row) => ({
    supplierUuid: row.supplierUuid,
    preferred: row.preferred ?? false,
    ean: toFormString(row.ean),
    externalProductCode: toFormString(row.externalProductCode),
    editing: toFormString(row.editing),
    deliveryTime: toFormString(row.deliveryTime, "0"),
    deliveryTimeUnit: row.deliveryTimeUnit ?? "",
    minOrderQty: toFormString(row.minOrderQty, "0.000"),
    minOrderQtyUnit: row.minOrderQtyUnit ?? "",
    orderSeries: toFormString(row.orderSeries, "0.000"),
    orderSeriesUnit: row.orderSeriesUnit ?? "",
  })),
  preferredLocations: product.preferredLocations.map((row) => ({
    locationUuid: row.locationUuid,
    preference: toFormString(row.preference, "1"),
    locationType: row.locationType ?? "",
    restockLevel: toFormString(row.restockLevel, "0.000"),
    restockLevelUnit: row.restockLevelUnit ?? "",
    restockLocationUuid: toFormString(row.restockLocationUuid),
    restockQty: toFormString(row.restockQty, "0.000"),
    restockQtyUnit: row.restockQtyUnit ?? "",
  })),
  priceStructures: product.priceStructures.map((row) => ({
    validFrom: toDateInput(row.validFrom),
    validUntil: toDateInput(row.validUntil),
    basePrice: toFormString(row.basePrice, "0.00"),
    markup: toFormString(row.markup, "0.00"),
    scrap: toFormString(row.scrap, "0.00"),
    priceUnit: row.priceUnit ?? "",
    quantitySurchargeEnabled: row.quantitySurchargeEnabled ?? false,
    quantitySurchargeBasis: row.quantitySurchargeBasis ?? "",
    quantitySurchargeTiers: row.quantitySurchargeTiers ?? [],
    groupDiscountEnabled: row.groupDiscountEnabled ?? false,
    groupDiscountBasis: row.groupDiscountBasis ?? "",
    groupDiscountTiers: row.groupDiscountTiers ?? [],
    lengthSurchargeEnabled: row.lengthSurchargeEnabled ?? false,
    lengthSurchargeTiers: row.lengthSurchargeTiers ?? [],
    qualitySurchargeEnabled: row.qualitySurchargeEnabled ?? false,
    qualitySurchargeTiers: row.qualitySurchargeTiers ?? [],
    lineDiscountEnabled: row.lineDiscountEnabled ?? false,
    lineDiscountTiers: row.lineDiscountTiers ?? [],
  })),
  sawingPrices: product.sawingPrices.map((row) => ({
    validFrom: toDateInput(row.validFrom),
    validUntil: toDateInput(row.validUntil),
    basePrice: toFormString(row.basePrice, "0.00"),
    priceUnit: row.priceUnit ?? "",
    mitreSurchargeEvenPct: toFormString(row.mitreSurchargeEvenPct, "0.00"),
    mitreSurchargeUnevenPct: toFormString(row.mitreSurchargeUnevenPct, "0.00"),
    quantityDiscountEnabled: row.quantityDiscountEnabled ?? false,
    quantityDiscountTiers: row.quantityDiscountTiers ?? [],
    lengthSurchargeEnabled: row.lengthSurchargeEnabled ?? false,
    lengthSurchargeTiers: row.lengthSurchargeTiers ?? [],
  })),
});
