import { z } from "zod";
import {
  articleGroups,
  ceStandards,
  certificaatOptions,
  countStockBases,
  customerLabelOptions,
  decimalPlacesOptions,
  deliveryTimeUnits,
  dispatchStrategies,
  featuresQualities,
  leadTimeMethods,
  priceTierBases,
  processedOptions,
  productDimensionShapes,
  productQualityStandards,
  purchasingUnits,
  salesUnitOptions,
  stockLabelBreakdowns,
  stockLabelTypes,
  stockModes,
  vatCodes,
  warehouseLocationTypes,
} from "@/lib/enums";
import { todayDateString } from "@/lib/helpers";

// Every enum on this form can be left unset — the reference shows "-empty-" as
// a real choice on almost all of them — so each is a union with "" rather than
// being made required.
const optionalEnum = <T extends readonly [string, ...string[]]>(values: T) =>
  z.union([z.enum(values), z.literal("")]).optional();

export const productAlternativeSchema = z.object({
  alternativeProductUuid: z.string().min(1, "Pick a product"),
  description: z.string().optional(),
});

export const productSupplierSchema = z.object({
  supplierUuid: z.string().min(1, "Pick a supplier"),
  preferred: z.boolean(),
  ean: z.string().optional(),
  externalProductCode: z.string().optional(),
  editing: z.string().optional(),
  deliveryTime: z.string().optional(),
  deliveryTimeUnit: optionalEnum(deliveryTimeUnits),
  minOrderQty: z.string().optional(),
  minOrderQtyUnit: optionalEnum(purchasingUnits),
  orderSeries: z.string().optional(),
  orderSeriesUnit: optionalEnum(purchasingUnits),
});

export const productPreferredLocationSchema = z.object({
  locationUuid: z.string().min(1, "Pick a location"),
  preference: z.string().optional(),
  locationType: optionalEnum(warehouseLocationTypes),
  restockLevel: z.string().optional(),
  restockLevelUnit: optionalEnum(salesUnitOptions),
  restockLocationUuid: z.string().optional(),
  restockQty: z.string().optional(),
  restockQtyUnit: optionalEnum(salesUnitOptions),
});

const priceTierSchema = z.object({
  from: z.string(),
  value: z.string(),
});

export const productPriceStructureSchema = z.object({
  validFrom: z.string().min(1, "A starting date is required"),
  validUntil: z.string().optional(),
  basePrice: z.string().optional(),
  markup: z.string().optional(),
  scrap: z.string().optional(),
  priceUnit: optionalEnum(purchasingUnits),
  quantitySurchargeEnabled: z.boolean(),
  quantitySurchargeBasis: optionalEnum(priceTierBases),
  quantitySurchargeTiers: z.array(priceTierSchema),
  groupDiscountEnabled: z.boolean(),
  groupDiscountBasis: optionalEnum(priceTierBases),
  groupDiscountTiers: z.array(priceTierSchema),
  lengthSurchargeEnabled: z.boolean(),
  lengthSurchargeTiers: z.array(priceTierSchema),
  qualitySurchargeEnabled: z.boolean(),
  qualitySurchargeTiers: z.array(priceTierSchema),
  lineDiscountEnabled: z.boolean(),
  lineDiscountTiers: z.array(priceTierSchema),
});

export const productSawingPriceSchema = z.object({
  validFrom: z.string().min(1, "A starting date is required"),
  validUntil: z.string().optional(),
  basePrice: z.string().optional(),
  priceUnit: optionalEnum(purchasingUnits),
  mitreSurchargeEvenPct: z.string().optional(),
  mitreSurchargeUnevenPct: z.string().optional(),
  quantityDiscountEnabled: z.boolean(),
  quantityDiscountTiers: z.array(priceTierSchema),
  lengthSurchargeEnabled: z.boolean(),
  lengthSurchargeTiers: z.array(priceTierSchema),
});

export const productSchema = z.object({
  // ── Identity ──────────────────────────────────────────────────────────────
  productCode: z.string().min(1, "Product code is required"),
  name: z.string().min(1, "Name is required"),
  productGroupUuid: z.string().optional(),
  revenueGroupUuid: z.string().optional(),
  companyUuid: z.string().optional(),
  priceGroup: z.string().optional(),
  ean: z.string().optional(),
  oldProductCode: z.string().optional(),
  materialGroup: z.string().optional(),
  commodityCode: z.string().optional(),
  scrap: z.boolean(),
  packaging: z.boolean(),
  descSalesPurchaseOverridable: z.boolean(),
  searchCode1: z.string().optional(),
  searchCode2: z.string().optional(),
  searchCode3: z.string().optional(),
  articleGroup: optionalEnum(articleGroups),

  groupLongDesc: z.string().optional(),
  groupShortDesc: z.string().optional(),
  productShortDesc: z.string().optional(),
  selectionCodes: z.array(z.string()),

  // ── Basis ─────────────────────────────────────────────────────────────────
  dimensionShape: optionalEnum(productDimensionShapes),
  length: z.string().optional(),
  widthDiameter: z.string().optional(),
  thickness: z.string().optional(),
  tradeLength: z.string().optional(),
  tradeLengthFixed: z.boolean(),
  overlength: z.string().optional(),
  weightPerM1: z.string().optional(),
  paintSurfacePerM1: z.string().optional(),
  featuresQuality: optionalEnum(featuresQualities),
  decimalPlaces: optionalEnum(decimalPlacesOptions),
  printDimensions: z.boolean(),
  weightTheoretical: z.string().optional(),
  weightTrade: z.string().optional(),
  weightGerman: z.string().optional(),
  standardsQuality: optionalEnum(productQualityStandards),
  tolerance: optionalEnum(productQualityStandards),
  ce: optionalEnum(ceStandards),
  options: z.array(z.string()),
  processedOption: optionalEnum(processedOptions),
  sourceProductUuid: z.string().optional(),
  industryNumber: z.string().optional(),

  // ── Classification features ───────────────────────────────────────────────
  classificationMaterial: z.string().optional(),
  classificationQualityGroup: z.string().optional(),
  classificationMainShape: z.string().optional(),
  classificationSubShape: z.string().optional(),
  classificationProcedure: z.string().optional(),
  classificationAppearance: z.string().optional(),
  classificationPerformance: z.string().optional(),

  // ── Purchase ──────────────────────────────────────────────────────────────
  purchasingUnit: optionalEnum(purchasingUnits),
  unitPrice: optionalEnum(purchasingUnits),
  deliveryTime: z.string().optional(),
  deliveryTimeUnit: optionalEnum(deliveryTimeUnits),
  orderSeries: z.string().optional(),
  blockedForPurchasing: z.boolean(),
  makingOrderAdvices: z.boolean(),
  visibleInProductionSchedule: z.boolean(),
  orderingAdviceNotes: z.string().optional(),
  productCodeOnPurchase: z.boolean(),
  maxLineQty: z.string().optional(),
  maxNetPrice: z.string().optional(),

  // ── Sales ─────────────────────────────────────────────────────────────────
  salesUnit: optionalEnum(salesUnitOptions),
  salesUnitPrice: optionalEnum(purchasingUnits),
  vatCode: optionalEnum(vatCodes),
  roundWeightPerPieceUp: z.boolean(),
  benorProduct: z.boolean(),
  productCodeOnQuoteOrderInvoice: z.boolean(),
  certificaat: optionalEnum(certificaatOptions),
  websiteExport: z.boolean(),
  websiteBlockedForSales: z.boolean(),
  descriptionProductShort: z.boolean(),
  showWeightPerPiece: z.boolean(),
  showPackagingPerPiece: z.boolean(),
  markProductGroup: z.boolean(),
  priceOnRequest: z.boolean(),
  minProfitMarginStock: z.string().optional(),
  minProfitMarginExWorks: z.string().optional(),
  minProfitMarginCrossDocking: z.string().optional(),
  severalBlockedForSales: z.boolean(),
  vehicleWithCraneRequired: z.boolean(),
  vehicleWithCanopyRequired: z.boolean(),
  alwaysReserveStock: z.boolean(),
  maxSalesLineQty: z.string().optional(),
  maxSalesNetPrice: z.string().optional(),
  handlingCosts: z.string().optional(),

  // ── Warehouse control ─────────────────────────────────────────────────────
  packagingMandatoryOnCompletion: z.boolean(),
  unloadingWorkorderInStockUnit: z.boolean(),
  receiptInLocationsWithLimitedDimensions: z.boolean(),
  goodsReceiptTerm: z.string().optional(),
  includeInCsvForStockLabels: z.boolean(),
  suggestLastUsedChargeInScanner: z.boolean(),
  stockLabelType: optionalEnum(stockLabelTypes),
  stockLabelBreakdown: optionalEnum(stockLabelBreakdowns),
  stockLabelPieces: z.string().optional(),
  toleranceUnloadingQty: z.string().optional(),
  toleranceUnloadingKg: z.string().optional(),
  toleranceCountQty: z.string().optional(),
  toleranceCountKg: z.string().optional(),
  tolerancePickingQty: z.string().optional(),
  tolerancePickingKg: z.string().optional(),
  toleranceProductionQty: z.string().optional(),
  customerLabelForPickingSlip: optionalEnum(customerLabelOptions),
  customerLabelForSawingSlip: optionalEnum(customerLabelOptions),
  customerLabelAtSurfTreatSlip: optionalEnum(customerLabelOptions),
  alwaysApproveManuallyWarehouseWorkorderLine: z.boolean(),
  alwaysApproveManuallyProductionWorkorderLine: z.boolean(),

  // ── Stock policy ──────────────────────────────────────────────────────────
  minStockMode: z.enum(stockModes),
  minStockMultiplier: z.string().optional(),
  minStockFixedValue: z.string().optional(),
  maxStockMode: z.enum(stockModes),
  maxStockMultiplier: z.string().optional(),
  maxStockFixedValue: z.string().optional(),
  leadTimeMethod: optionalEnum(leadTimeMethods),
  leadTime: z.string().optional(),
  reviewPeriod: z.string().optional(),
  orderCostsPurchasingSide: z.string().optional(),
  orderCostsLogistics: z.string().optional(),
  stockOpOrderSeries: z.string().optional(),
  minOrderQty: z.string().optional(),
  useStockOpForThisProduct: z.boolean(),
  orderOnMonday: z.boolean(),
  orderOnTuesday: z.boolean(),
  orderOnWednesday: z.boolean(),
  orderOnThursday: z.boolean(),
  orderOnFriday: z.boolean(),
  capitalCost: z.string().optional(),
  warehouseCost: z.string().optional(),
  b2StockoutPct1: z.string().optional(),
  b2StockoutPct2: z.string().optional(),
  handling: z.string().optional(),
  transport: z.string().optional(),
  pacClassification: z.string().optional(),
  orderAdviceCode: z.string().optional(),

  // ── Stock control ─────────────────────────────────────────────────────────
  stockUnit: optionalEnum(salesUnitOptions),
  scrapProductUuid: z.string().optional(),
  transferProductUuid: z.string().optional(),
  packagingProductUuid: z.string().optional(),
  cdLocationUuid: z.string().optional(),
  stockProduct: z.boolean(),
  stockProductSince: z.string().optional(),
  standardProduct: z.boolean(),
  groupProduct: z.boolean(),
  batchRegistration: z.boolean(),
  batchRegisterLength: z.boolean(),
  batchLengthMinimum: z.string().optional(),
  batchLengthInterval: z.string().optional(),
  batchLengthRemainderTolerance: z.string().optional(),
  batchRegisterWidth: z.boolean(),
  batchWidthMinimum: z.string().optional(),
  batchWidthInterval: z.string().optional(),
  batchUseOptimization: z.boolean(),
  batchCharge: z.boolean(),
  batchDispatchStrategy: optionalEnum(dispatchStrategies),
  batchDoNotSplitPerBatch: z.boolean(),
  batchPlateNumber: z.boolean(),
  batchPerPiece: z.boolean(),
  batchNumber: z.boolean(),
  countFrequency: z.string().optional(),
  lastCountDate: z.string().optional(),
  nextCountTargetDate: z.string().optional(),
  countStockBasis: optionalEnum(countStockBases),
  countBelowQuantity: z.string().optional(),
  countBelowUnit: optionalEnum(salesUnitOptions),

  // ── Optimization criteria ─────────────────────────────────────────────────
  optTradeLengthTolerance: z.string().optional(),
  optEndSpace: z.string().optional(),
  optClamping: z.string().optional(),
  optOffcutMinLength: z.string().optional(),
  optOffcutPreferredMin: z.string().optional(),
  optClampingEdge: z.string().optional(),
  optFactorBundles: z.string().optional(),
  optFactorPriorityLocationType: z.string().optional(),
  optFactorSawingCuts: z.string().optional(),
  optFactorCreatedOffcuts: z.string().optional(),
  optFactorCreatedScrapPieces: z.string().optional(),
  optFactorUsedTradeLengths: z.string().optional(),
  optFactorUsedOffcuts: z.string().optional(),
  optFactorScrapPieceLength: z.string().optional(),
  optFactorOffcutsBelowPreferred: z.string().optional(),
  optFactorLengthCutoffs: z.string().optional(),
  optAllowLongestOffcuts: z.boolean(),

  // ── Valuation ─────────────────────────────────────────────────────────────
  replacementPrice: z.string().optional(),
  basePrice: z.string().optional(),
  markup: z.string().optional(),
  fixedSalesPrice: z.string().optional(),
  averagePurchasePrice: z.string().optional(),
  priceUnit: optionalEnum(salesUnitOptions),
  priceDate: z.string().optional(),
  fixedSettlementPrice: z.string().optional(),
  valuationInternalSurcharge: z.string().optional(),
  valuationExternalSurcharge: z.string().optional(),
  valuationStartDate: z.string().optional(),
  fspCalculationBasis: z.string().optional(),

  // ── Misc ──────────────────────────────────────────────────────────────────
  technicalStock: z.string(),
  theoreticalWeight: z.string(),
  weightUnit: optionalEnum(salesUnitOptions),
  showOnWebsite: z.boolean(),
  preferred: z.boolean(),
  externalProductCode: z.string().optional(),
  editing: z.string().optional(),
  remarks: z.string().optional(),
  documents: z
    .array(z.object({ id: z.string(), fileName: z.string() }))
    .optional(),

  // ── Child rows ────────────────────────────────────────────────────────────
  alternatives: z.array(productAlternativeSchema),
  suppliers: z.array(productSupplierSchema),
  preferredLocations: z.array(productPreferredLocationSchema),
  priceStructures: z.array(productPriceStructureSchema),
  sawingPrices: z.array(productSawingPriceSchema),
});

export type ProductFormValues = z.infer<typeof productSchema>;
export type ProductAlternativeFormValues = z.infer<
  typeof productAlternativeSchema
>;
export type ProductSupplierFormValues = z.infer<typeof productSupplierSchema>;
export type ProductPreferredLocationFormValues = z.infer<
  typeof productPreferredLocationSchema
>;
export type ProductPriceStructureFormValues = z.infer<
  typeof productPriceStructureSchema
>;
export type ProductSawingPriceFormValues = z.infer<
  typeof productSawingPriceSchema
>;

export const EMPTY_PRICE_STRUCTURE: ProductPriceStructureFormValues = {
  validFrom: todayDateString(),
  validUntil: "",
  basePrice: "0.00",
  markup: "0.00",
  scrap: "0.00",
  priceUnit: "",
  quantitySurchargeEnabled: false,
  quantitySurchargeBasis: "",
  quantitySurchargeTiers: [],
  groupDiscountEnabled: false,
  groupDiscountBasis: "",
  groupDiscountTiers: [],
  lengthSurchargeEnabled: false,
  lengthSurchargeTiers: [],
  qualitySurchargeEnabled: false,
  qualitySurchargeTiers: [],
  lineDiscountEnabled: false,
  lineDiscountTiers: [],
};

export const EMPTY_SAWING_PRICE: ProductSawingPriceFormValues = {
  validFrom: todayDateString(),
  validUntil: "",
  basePrice: "0.00",
  priceUnit: "",
  mitreSurchargeEvenPct: "0.00",
  mitreSurchargeUnevenPct: "0.00",
  quantityDiscountEnabled: false,
  quantityDiscountTiers: [],
  lengthSurchargeEnabled: false,
  lengthSurchargeTiers: [],
};

export const DEFAULT_PRODUCT: ProductFormValues = {
  productCode: "",
  name: "",
  productGroupUuid: "",
  revenueGroupUuid: "",
  companyUuid: "",
  priceGroup: "",
  ean: "",
  oldProductCode: "",
  materialGroup: "",
  commodityCode: "",
  scrap: false,
  packaging: false,
  descSalesPurchaseOverridable: false,
  searchCode1: "",
  searchCode2: "",
  searchCode3: "",
  articleGroup: "",

  groupLongDesc: "",
  groupShortDesc: "",
  productShortDesc: "",
  selectionCodes: [],

  dimensionShape: "",
  length: "",
  widthDiameter: "",
  thickness: "",
  tradeLength: "0.00",
  tradeLengthFixed: false,
  overlength: "0.00",
  weightPerM1: "0.0000",
  paintSurfacePerM1: "0.0000",
  featuresQuality: "",
  decimalPlaces: "0",
  printDimensions: false,
  weightTheoretical: "0.000",
  weightTrade: "0.000",
  weightGerman: "0.000",
  standardsQuality: "",
  tolerance: "",
  ce: "",
  options: [],
  processedOption: "",
  sourceProductUuid: "",
  industryNumber: "",

  classificationMaterial: "",
  classificationQualityGroup: "",
  classificationMainShape: "",
  classificationSubShape: "",
  classificationProcedure: "",
  classificationAppearance: "",
  classificationPerformance: "",

  purchasingUnit: "",
  unitPrice: "",
  deliveryTime: "0",
  deliveryTimeUnit: "",
  orderSeries: "0",
  blockedForPurchasing: false,
  makingOrderAdvices: false,
  visibleInProductionSchedule: false,
  orderingAdviceNotes: "",
  productCodeOnPurchase: false,
  maxLineQty: "0.00",
  maxNetPrice: "0.00",

  salesUnit: "",
  salesUnitPrice: "",
  vatCode: "",
  roundWeightPerPieceUp: false,
  benorProduct: false,
  productCodeOnQuoteOrderInvoice: false,
  certificaat: "",
  websiteExport: false,
  websiteBlockedForSales: false,
  descriptionProductShort: false,
  showWeightPerPiece: false,
  showPackagingPerPiece: false,
  markProductGroup: false,
  priceOnRequest: false,
  minProfitMarginStock: "0.00",
  minProfitMarginExWorks: "0.00",
  minProfitMarginCrossDocking: "0.00",
  severalBlockedForSales: false,
  vehicleWithCraneRequired: false,
  vehicleWithCanopyRequired: false,
  alwaysReserveStock: false,
  maxSalesLineQty: "0.000",
  maxSalesNetPrice: "0.00",
  handlingCosts: "0.00",

  packagingMandatoryOnCompletion: false,
  unloadingWorkorderInStockUnit: false,
  receiptInLocationsWithLimitedDimensions: false,
  goodsReceiptTerm: "0",
  includeInCsvForStockLabels: false,
  suggestLastUsedChargeInScanner: false,
  stockLabelType: "",
  stockLabelBreakdown: "per_line_bundle",
  stockLabelPieces: "1",
  toleranceUnloadingQty: "0.00",
  toleranceUnloadingKg: "0.00",
  toleranceCountQty: "0.00",
  toleranceCountKg: "0.00",
  tolerancePickingQty: "0.00",
  tolerancePickingKg: "0.00",
  toleranceProductionQty: "0.00",
  customerLabelForPickingSlip: "",
  customerLabelForSawingSlip: "",
  customerLabelAtSurfTreatSlip: "",
  alwaysApproveManuallyWarehouseWorkorderLine: false,
  alwaysApproveManuallyProductionWorkorderLine: false,

  minStockMode: "multiplier",
  minStockMultiplier: "1.00",
  minStockFixedValue: "0.000",
  maxStockMode: "multiplier",
  maxStockMultiplier: "3.00",
  maxStockFixedValue: "0.000",
  leadTimeMethod: "manually",
  leadTime: "0",
  reviewPeriod: "0",
  orderCostsPurchasingSide: "0.00",
  orderCostsLogistics: "0.00",
  stockOpOrderSeries: "0.000",
  minOrderQty: "0.000",
  useStockOpForThisProduct: false,
  orderOnMonday: true,
  orderOnTuesday: true,
  orderOnWednesday: true,
  orderOnThursday: true,
  orderOnFriday: true,
  capitalCost: "0.0000",
  warehouseCost: "0.0000",
  b2StockoutPct1: "0.00",
  b2StockoutPct2: "0.00",
  handling: "0.0000",
  transport: "0.0000",
  pacClassification: "",
  orderAdviceCode: "",

  stockUnit: "",
  scrapProductUuid: "",
  transferProductUuid: "",
  packagingProductUuid: "",
  cdLocationUuid: "",
  stockProduct: false,
  stockProductSince: "",
  standardProduct: false,
  groupProduct: false,
  batchRegistration: false,
  batchRegisterLength: false,
  batchLengthMinimum: "0.00",
  batchLengthInterval: "0.00",
  batchLengthRemainderTolerance: "0.00",
  batchRegisterWidth: false,
  batchWidthMinimum: "0.00",
  batchWidthInterval: "0.00",
  batchUseOptimization: false,
  batchCharge: false,
  batchDispatchStrategy: "lifo",
  batchDoNotSplitPerBatch: false,
  batchPlateNumber: false,
  batchPerPiece: false,
  batchNumber: false,
  countFrequency: "0",
  lastCountDate: "",
  nextCountTargetDate: "",
  countStockBasis: "technical",
  countBelowQuantity: "0.000",
  countBelowUnit: "",

  optTradeLengthTolerance: "0",
  optEndSpace: "0",
  optClamping: "0",
  optOffcutMinLength: "0",
  optOffcutPreferredMin: "0",
  optClampingEdge: "0",
  optFactorBundles: "0",
  optFactorPriorityLocationType: "0",
  optFactorSawingCuts: "0",
  optFactorCreatedOffcuts: "0",
  optFactorCreatedScrapPieces: "0",
  optFactorUsedTradeLengths: "0",
  optFactorUsedOffcuts: "0",
  optFactorScrapPieceLength: "0",
  optFactorOffcutsBelowPreferred: "0",
  optFactorLengthCutoffs: "0",
  optAllowLongestOffcuts: false,

  replacementPrice: "0.00",
  basePrice: "0.00",
  markup: "0.00",
  fixedSalesPrice: "0.00",
  averagePurchasePrice: "0.00",
  priceUnit: "",
  priceDate: "",
  fixedSettlementPrice: "0.00000",
  valuationInternalSurcharge: "0.00",
  valuationExternalSurcharge: "0.00",
  valuationStartDate: "",
  fspCalculationBasis: "0.00",

  technicalStock: "0.000",
  theoreticalWeight: "0.0000",
  weightUnit: "",
  showOnWebsite: false,
  preferred: false,
  externalProductCode: "",
  editing: "",
  remarks: "",
  documents: [],

  alternatives: [],
  suppliers: [],
  preferredLocations: [],
  priceStructures: [],
  sawingPrices: [],
};
