import { z } from "zod";
import {
  articleGroups,
  ceStandards,
  certificaatOptions,
  customerLabelOptions,
  decimalPlacesOptions,
  deliveryTimeUnits,
  featuresQualities,
  leadTimeMethods,
  processedOptions,
  productQualityStandards,
  productShapes,
  purchasingUnits,
  revenueGroups,
  salesUnitOptions,
  stockLabelPrintingOptions,
  stockLabelTypes,
  stockModes,
  vatCodes,
} from "@/lib/enums";

export const supplierSchema = z.object({
  supplierCompanyUuid: z.string().min(1, "Supplier is required"),
  preferred: z.boolean(),
  ean: z.string().optional(),
  externalProductCode: z.string().optional(),
  editing: z.string().optional(),
  deliveryTime: z.coerce.number(),
  deliveryTimeUnit: z.enum(deliveryTimeUnits).optional(),
  moq: z.string(),
  moqUnit: z.enum(purchasingUnits).optional(),
  orderSeries: z.coerce.number(),
  orderSeriesUnit: z.enum(purchasingUnits).optional(),
});

export type ProductGroupSupplierValues = z.infer<typeof supplierSchema>;

export const EMPTY_SUPPLIER: ProductGroupSupplierValues = {
  supplierCompanyUuid: "",
  preferred: false,
  ean: "",
  externalProductCode: "",
  editing: "",
  deliveryTime: 0,
  deliveryTimeUnit: undefined,
  moq: "0.000",
  moqUnit: undefined,
  orderSeries: 0,
  orderSeriesUnit: undefined,
};

export const productGroupSchema = z.object({
  parentUuid: z.string().nullable().optional(),
  name: z.string().min(1, "Name is required"),
  productShape: z.enum(productShapes).optional(),
  groupLongDesc: z.string().optional(),
  groupShortDesc: z.string().optional(),
  productShapeDesc: z.string().optional(),
  materialGroup: z.string().optional(),
  commodity: z.string().optional(),
  scrap: z.boolean(),
  packaging: z.boolean(),
  descSalesPurchaseOverridable: z.boolean(),
  searchCode1: z.string().optional(),
  searchCode2: z.string().optional(),
  searchCode3: z.string().optional(),
  articleGroup: z.enum(articleGroups).optional(),

  // Dimensions
  length: z.string().optional(),
  width: z.string().optional(),
  thickness: z.string().optional(),
  decimalPlaces: z.enum(decimalPlacesOptions).optional(),
  printDimensions: z.boolean(),

  // Features
  weight: z.string().optional(),
  paintSurface: z.string().optional(),
  featuresQuality: z.enum(featuresQualities).optional(),
  weightTheoretical: z.string(),
  weightTrade: z.string(),
  weightGerman: z.string(),

  // Standards
  standardsQuality: z.enum(productQualityStandards).optional(),
  tolerance: z.enum(productQualityStandards).optional(),
  ce: z.enum(ceStandards).optional(),
  options: z.array(z.string()).optional(),
  processedOption: z.enum(processedOptions).optional(),
  sourceProduct: z.string().optional(),
  industryNumber: z.string().optional(),

  // Purchase
  purchasingUnit: z.enum(purchasingUnits).optional(),
  unitPrice: z.enum(purchasingUnits).optional(),
  deliveryTime: z.coerce.number(),
  deliveryTimeUnit: z.enum(deliveryTimeUnits).optional(),
  orderSeries: z.coerce.number(),
  blockedForPurchasing: z.boolean(),
  makingOrderAdvices: z.boolean(),
  orderingAdviceNotes: z.string().optional(),
  productCodeOnPurchase: z.boolean(),
  maxLineQty: z.string(),
  maxNetPrice: z.string(),

  // Warehouse Control
  packagingMandatoryOnCompletion: z.boolean(),
  receiptInLocationsWithLimitedDimensions: z.boolean(),
  goodsReceiptTerm: z.coerce.number(),
  includeInCsvForStockLabels: z.boolean(),
  suggestLastUsedChargeInScanner: z.boolean(),
  stockLabelType: z.enum(stockLabelTypes).optional(),
  stockLabelPrinting: z.enum(stockLabelPrintingOptions).optional(),
  toleranceUnloadingQty: z.string(),
  toleranceUnloadingKg: z.string(),
  toleranceCountQty: z.string(),
  toleranceCountKg: z.string(),
  tolerancePickingQty: z.string(),
  tolerancePickingKg: z.string(),
  toleranceProductionQty: z.string(),
  customerLabelForPickingSlip: z.enum(customerLabelOptions).optional(),
  customerLabelForSawingSlip: z.enum(customerLabelOptions).optional(),
  customerLabelAtSurfTreatSlip: z.enum(customerLabelOptions).optional(),
  alwaysApproveManuallyWarehouseWorkorderLine: z.boolean(),
  alwaysApproveManuallyProductionWorkorderLine: z.boolean(),

  // Stock Policy
  minStockMode: z.enum(stockModes),
  minStockMultiplier: z.string(),
  minStockFixedValue: z.string(),
  minStockUnit: z.string().optional(),
  maxStockMode: z.enum(stockModes),
  maxStockMultiplier: z.string(),
  maxStockFixedValue: z.string(),
  maxStockUnit: z.string().optional(),
  leadTimeMethod: z.enum(leadTimeMethods),
  leadTime: z.coerce.number(),
  reviewPeriod: z.coerce.number(),
  orderCostsPurchasingSide: z.string(),
  orderCostsLogistics: z.string(),
  stockOpOrderSeries: z.string(),
  minOrderQty: z.string(),
  useStockOpForThisProduct: z.boolean(),
  orderOnMonday: z.boolean(),
  orderOnTuesday: z.boolean(),
  orderOnWednesday: z.boolean(),
  orderOnThursday: z.boolean(),
  orderOnFriday: z.boolean(),
  capitalCost: z.string(),
  warehouseCost: z.string(),
  b2StockoutPct1: z.string(),
  b2StockoutPct2: z.string(),
  handling: z.string(),
  transport: z.string(),
  pacClassification: z.string().optional(),
  orderAdviceCode: z.string().optional(),

  // Sales
  revenueGroup: z.enum(revenueGroups).optional(),
  salesUnit: z.enum(salesUnitOptions).optional(),
  salesUnitPrice: z.enum(purchasingUnits).optional(),
  vatCode: z.enum(vatCodes).optional(),
  roundWeightPerPieceUp: z.boolean(),
  benorProduct: z.boolean(),
  productCodeOnQuoteOrderInvoice: z.boolean(),
  certificaat: z.enum(certificaatOptions).optional(),
  websiteExport: z.boolean(),
  websiteBlockedForSales: z.boolean(),
  descriptionProductShort: z.boolean(),
  showWeightPerPiece: z.boolean(),
  showPackagingPerPiece: z.boolean(),
  markProductGroup: z.boolean(),
  priceOnRequest: z.boolean(),
  minProfitMarginStock: z.string(),
  minProfitMarginExWorks: z.string(),
  minProfitMarginCrossDocking: z.string(),
  severalBlockedForSales: z.boolean(),
  vehicleWithCraneRequired: z.boolean(),
  vehicleWithCanopyRequired: z.boolean(),
  alwaysReserveStock: z.boolean(),
  maxSalesLineQty: z.string(),
  maxSalesNetPrice: z.string(),
  handlingCosts: z.string(),

  // Suppliers (one row per supplier; one flagged preferred)
  suppliers: z.array(supplierSchema),

  // Documents
  documents: z
    .array(z.object({ id: z.string(), fileName: z.string() }))
    .optional(),
});

export type ProductGroupFormValues = z.infer<typeof productGroupSchema>;

export const DEFAULT_PRODUCT_GROUP: ProductGroupFormValues = {
  parentUuid: null,
  name: "",
  productShape: undefined,
  groupLongDesc: "",
  groupShortDesc: "",
  productShapeDesc: "",
  materialGroup: "",
  commodity: "",
  scrap: false,
  packaging: false,
  descSalesPurchaseOverridable: false,
  searchCode1: "",
  searchCode2: "",
  searchCode3: "",
  articleGroup: undefined,
  length: "",
  width: "",
  thickness: "",
  decimalPlaces: "0",
  printDimensions: false,
  weight: "",
  paintSurface: "",
  featuresQuality: undefined,
  weightTheoretical: "0.000",
  weightTrade: "0.000",
  weightGerman: "0.000",
  standardsQuality: undefined,
  tolerance: undefined,
  ce: undefined,
  options: [],
  processedOption: undefined,
  sourceProduct: "",
  industryNumber: "",
  purchasingUnit: undefined,
  unitPrice: undefined,
  deliveryTime: 0,
  deliveryTimeUnit: undefined,
  orderSeries: 0,
  blockedForPurchasing: false,
  makingOrderAdvices: false,
  orderingAdviceNotes: "",
  productCodeOnPurchase: false,
  maxLineQty: "0.000",
  maxNetPrice: "0.00",
  packagingMandatoryOnCompletion: false,
  receiptInLocationsWithLimitedDimensions: false,
  goodsReceiptTerm: 0,
  includeInCsvForStockLabels: false,
  suggestLastUsedChargeInScanner: false,
  stockLabelType: undefined,
  stockLabelPrinting: undefined,
  toleranceUnloadingQty: "0.00",
  toleranceUnloadingKg: "0.00",
  toleranceCountQty: "0.00",
  toleranceCountKg: "0.00",
  tolerancePickingQty: "0.00",
  tolerancePickingKg: "0.00",
  toleranceProductionQty: "0.00",
  customerLabelForPickingSlip: undefined,
  customerLabelForSawingSlip: undefined,
  customerLabelAtSurfTreatSlip: undefined,
  alwaysApproveManuallyWarehouseWorkorderLine: false,
  alwaysApproveManuallyProductionWorkorderLine: false,
  minStockMode: "multiplier",
  minStockMultiplier: "1.00",
  minStockFixedValue: "0.000",
  minStockUnit: "",
  maxStockMode: "multiplier",
  maxStockMultiplier: "3.00",
  maxStockFixedValue: "0.000",
  maxStockUnit: "",
  leadTimeMethod: "manually",
  leadTime: 0,
  reviewPeriod: 0,
  orderCostsPurchasingSide: "0.00",
  orderCostsLogistics: "0.00",
  stockOpOrderSeries: "0.000",
  minOrderQty: "0.000",
  useStockOpForThisProduct: false,
  orderOnMonday: true,
  orderOnTuesday: true,
  orderOnWednesday: true,
  orderOnThursday: true,
  orderOnFriday: true,
  capitalCost: "0.0000",
  warehouseCost: "0.0000",
  b2StockoutPct1: "0.00",
  b2StockoutPct2: "0.00",
  handling: "0.0000",
  transport: "0.0000",
  pacClassification: "",
  orderAdviceCode: "",
  revenueGroup: undefined,
  salesUnit: undefined,
  salesUnitPrice: undefined,
  vatCode: undefined,
  roundWeightPerPieceUp: false,
  benorProduct: false,
  productCodeOnQuoteOrderInvoice: false,
  certificaat: undefined,
  websiteExport: false,
  websiteBlockedForSales: false,
  descriptionProductShort: false,
  showWeightPerPiece: false,
  showPackagingPerPiece: false,
  markProductGroup: false,
  priceOnRequest: false,
  minProfitMarginStock: "0.00",
  minProfitMarginExWorks: "0.00",
  minProfitMarginCrossDocking: "0.00",
  severalBlockedForSales: false,
  vehicleWithCraneRequired: false,
  vehicleWithCanopyRequired: false,
  alwaysReserveStock: false,
  maxSalesLineQty: "0.000",
  maxSalesNetPrice: "0.00",
  handlingCosts: "0.00",
  suppliers: [],
  documents: [],
};
